config/routes.rb
Absci::Application.routes.draw do
  get "users/show"

  resources :antibodies do
    post :vote, on: :member
    resources :protocols, only: [:new, :create]
  end
  
  resources :protocols, except: [:new, :create]

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  root :to => 'pages#home'

  get 'about' => 'pages#about'
  get 'products' => 'pages#products'
  get 'team' => 'pages#team'
  

end

app/models/antibody.rb
class Antibody < ActiveRecord::Base
  attr_accessible :isotype, :product, :target, :vendor, :antibody

  validates_presence_of :product
  validates_presence_of :antibody
  validates_presence_of :target
  validates_presence_of :vendor
  validates_presence_of :isotype


  has_many :protocols, dependent: :destroy

  has_reputation :votes, source: :user, aggregated_by: :sum
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
  attr_accessible :blocking_buffer, :cell, :description, :detection, :gel,
  								:lysis_buffer, :membrane, :primary_description, :secondary_description,
  								:statement, :research_application, :transfer, :washes

  validates_presence_of :blocking_buffer
  validates_presence_of :cell
  validates_presence_of :description
  validates_presence_of :detection
  validates_presence_of :gel
  validates_presence_of :lysis_buffer
  validates_presence_of :membrane
  validates_presence_of :primary_description
  validates_presence_of :secondary_description
  validates_presence_of :research_application
  validates_presence_of :statement
  validates_presence_of :transfer
  validates_presence_of :washes

  belongs_to :user
  belongs_to :antibody

	# Ensures the presence of a user, and that a user matches with a given protocol
  validates_presence_of :user
  validates_presence_of :antibody
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :image

  has_many :protocols, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/antibodies_controller.rb
class AntibodiesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @search = Antibody.search(params[:q])
    @antibodies = @search.result.page(params[:page]).per_page(20).find_with_reputation(:votes, :all, order: "votes desc")

    respond_to do |format|
      format.html
      format.json { render json: @antibodies }
    end
  end

  def show
    @antibodies = @search.result

    @antibody = Antibody.find(params[:id])
    if user_signed_in? 
      @protocols = @antibody.protocols.paginate(page: params[:page]).per_page(5)
    else
      @antibody
    end
    respond_to do |format|
      format.html
      format.json { render json: @antibody }
    end
  end

  def new
    @antibody = Antibody.new

    respond_to do |format|
      format.html
      format.json { render json: @antibody }
    end
  end

  def edit
    if user_signed_in?
      @antibody
    else
      @antibody
    end
  end

  def create
    @antibody = Antibody.new(params[:antibody])

    respond_to do |format|
      if @antibody.save
        format.html { redirect_to @antibody, notice: 'Antibody was successfully created.' }
        format.json { render json: @antibody, status: :created, location: @antibody }
      else
        format.html { render action: "new" }
        format.json { render json: @antibody.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @antibody = Antibody.find(params[:id])

    respond_to do |format|
      if @antibody.update_attributes(params[:antibody])
        format.html { redirect_to @antibody, notice: 'Antibody was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @antibody.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @antibody = Antibody.find(params[:id])
    @antibody.destroy

    respond_to do |format|
      format.html { redirect_to antibodies_url }
      format.json { head :no_content }
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @antibody = Antibody.find(params[:id])
    @antibody.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for your rating!"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_search
  
  protected
  
  def set_search
    @search = Antibody.search(params[:q])
    @antibodies = @search.result
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in? 
      @user = current_user
      @protocols = @user.protocols.paginate(page: params[:page])
    end
  end

  def about
  end

  def contact
  end

  def products
  end

  def team
  end
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def index
    @protocols = Protocol.order("created_at desc").page(params[:page]).per_page(4)

    respond_to do |format|
      format.html
      format.json { render json: @protocols }
    end
  end

  def show
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @protocol }
    end
  end

  def new
    @protocol = current_user.protocols.new
    @antibody = Antibody.find(params[:antibody_id])

    respond_to do |format|
      format.html
      format.json { render json: @protocol }
    end
  end

  def edit
    @protocol = current_user.protocols.find(params[:id])
  end

  def create
    @protocol = current_user.protocols.new(params[:protocol])
    @antibody = Antibody.find(params[:antibody_id])

    @protocol.antibody = @antibody

    respond_to do |format|
      if @protocol.save
        format.html { redirect_to @antibody, notice: 'Protocol was successfully created.' }
        format.json { render json: @protocol, status: :created, location: @protocol }
      else
        format.html { render action: "new" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @protocol = current_user.protocols.find(params[:id])

    respond_to do |format|
      if @protocol.update_attributes(params[:protocol])
        format.html { redirect_to @protocol, notice: 'Protocol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @protocol = current_user.protocols.find(params[:id])
    @protocol.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @protocols = @user.protocols.paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise_mappings[:user]
  end
end

app/views/antibodies/_antibody.html.erb
<% if user_signed_in? %>
	<div class="box">
	 	<h5>Target: </h5><%= antibody.target %>
	  <h5>Antibody: </h5><%= antibody.antibody %>
 	<p class="details">
	  	<h5>Vendor: </h5><%= antibody.vendor %>
	    	<br />
	  	<h5>Isotype: </h5><%= antibody.isotype %>
	   		<br />
	   	<h5>Approval Rating: <%= antibody.reputation_for(:votes).to_i %></h5>
		 	<h5>Protocols: <%= antibody.protocols.count %></h5>
	   </p>
	   <%= link_to 'Show', antibody %>
	</div>
<% else %>
	<div class="box">
	  <h5>Target: </h5><%= antibody.target %>
	  <h5>Antibody: </h5><%= antibody.antibody %>
	<p class="details">
  	<h5>Vendor: </h5><%= antibody.vendor %>
  		<br />
  	<h5>Product: </h5><%= antibody.product %>
	   	<br />
	  <h5>Isotype: </h5><%= antibody.isotype %>
	 		<br />
   	<h5>Approval Rating: <%= antibody.reputation_for(:votes).to_i %></h5>	   	
   	<h5>Protocols: <%= antibody.protocols.count %></h5>
	</p>
	</div>
<% end %>

app/views/antibodies/_form.html.erb
<%= simple_form_for(@antibody, html: { class: "form-horizontal"}) do |f| %>

  <%= f.input :target, 	 :placeholder => "Target" %>
  <%= f.input :antibody, :placeholder => "Antibody" %>
  <%= f.input :vendor, 	 :placeholder => "Vendor" %>
  <%= f.input :product,  :placeholder => "Product ID" %>
  <%= f.input :isotype,  :placeholder => "Isotype" %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/antibodies/edit.html.erb
<h1>Editing antibody</h1>

<%= render 'form' %>

<%= link_to 'Show', @antibody %> |
<%= link_to 'Back', antibodies_path %>

app/views/antibodies/index.html.erb
<div id="antibodies">
  <%= render @antibodies %>
</div>

<%= will_paginate @antibodies %>

app/views/antibodies/new.html.erb
<h1>New antibody</h1>

<%= render 'form' %>

<%= link_to 'Back', antibodies_path %>

app/views/antibodies/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
			  <b>Target:</b>
			  <%= @antibody.target %>
			</p>
			<p>
			  <b>Antibody:</b>
			  <%= @antibody.antibody %>
			</p>
			<p>
			  <b>Vendor:</b>
			  <%= @antibody.vendor %>
			</p>
			<p>
			  <b>Product:</b>
			  <%= @antibody.product %>
			</p>
			<p>
			  <b>Isotype:</b>
			  <%= @antibody.isotype %>
			</p>
			<p>
				<%= link_to "Add Protocol",  new_antibody_protocol_path(@antibody), class: "btn btn-success" %>
			</p>
			<br />	
			<p>
				<%= pluralize @antibody.reputation_for(:votes).to_i, "rating" %> |
				<%= link_to "Approve", vote_antibody_path(@antibody, type: "up"), method: "post" %> | 
				<%= link_to "Disapprove", vote_antibody_path(@antibody, type: "down"), method: "post" %>
			</p>
		</div>
		<% if @antibody.protocols.any? %>
		</br>
		<h4>Protocols for <%= @antibody.antibody %>:</h4>
			<%= render :partial => 'protocols/protocol' %>
			<%= will_paginate @protocols %>
		<% else %>
			<div class="container-fluid">
					<div class="text-center">
						<div class="alert alert-info">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							<strong>No protocols associated with this antibody yet.</strong><br />
						</div>
					</div>
			</div>
		<% end %>
 
		<%= link_to 'Back', antibodies_path %>

	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
	<div class="navbar-inner">
	  <div class="container">
	    <footer>
	      <small>
	        &copy; 2014 by Sciero. All Rights Reserved.
	      </small>
	    </footer>
	  </div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <!-- Allows for collapsible menus on mobile devices -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </a>
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Sciero", root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li><%= link_to "About", about_path %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to "Products", products_path %></li>
          <li class="divider-vertical"></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li class="navbar-search pull-right">
              <%= search_form_for @search do |f| %>
                <%= f.text_field :target_or_antibody_or_vendor_or_isotype_cont, class: "input-medium search-query", placeholder: "Search for antibodies..." %>
              <% end %>
            </li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Sciero</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,600,700" rel="stylesheet" />
		<script src="jquery.min.js"></script>
		<script src="config.js"></script>
		<script src="javascripts/skel.min.js"></script>
		<noscript>
			<link rel="stylesheet" href="stylesheets/skel-noscript.css" />
			<link rel="stylesheet" href="stylesheets/style.css" />
			<link rel="stylesheet" href="stylesheets/style-desktop.css" />
		</noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="stylesheets/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><link rel="stylesheet" href="javascripts/ie8.css" /><![endif]-->
		<!--[if lte IE 7]><link rel="stylesheet" href="stylesheets/ie7.css" /><![endif]-->
	</head>
	<body>
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>

		<!-- Nav -->
			<nav id="nav">
				<ul class="container">
					<li><a href="#top">Home</a></li>
					<li><a href="#about">About</a></li>
					<li><a href="#product">Products</a></li>
					<li><a href="#sign_up">Sign Up</a></li>
				</ul>
			</nav>

		<!-- Home -->
			<div class="wrapper wrapper-style1 wrapper-first">
				<article class="container" id="top">
					<div class="row">
						<div class="4u">
							<span class="me image image-full"><%= image_tag("dna_strand.png") %></span>
						</div>
						<div class="8u">
							<header>
								<h1>Welcome to <strong>Sciero</strong>.</h1>
							</header>
							<p>Scientific Research. <strong>Redefined</strong>.</p>
							<a href="#work" class="button button-big">What We Do</a>
						</div>
					</div>
				</article>
			</div>

		<!-- About -->
			<div class="wrapper wrapper-style2">
				<article id="about">
					<header>
						<h2>We do awesome.</h2>
						<span>A high-level approach to every project and feature. We do...</span>
					</header>
					<div class="container">
						<div class="row">
							<div class="4u">
								<section class="box box-style1">
									<span class="fa featured fa-lightbulb-o"></span>
									<h3>Tools</h3>
									<p>Design innovative tools at the intersection of deep information and biomedical research.</p>
								</section>
							</div>
							<div class="4u">
								<section class="box box-style1">
									<span class="fa featured fa-gear"></span>
									<h3>Usability</h3>
									<p>Aim to achieve the highest usability standard that is streamlined and accessible for every scientist.</p>
								</section>
							</div>
							<div class="4u">
								<section class="box box-style1">
									<span class="fa featured fa-signal"></span>
									<h3>Analytics</h3>
									<p>Redefine the conventional means of analysis by increasing the efficiency of data collection.</p>
								</section>
							</div>
						</div>
					</div>
					<footer>
						<a href="#product" class="button button-big">Products</a>
					</footer>
				</article>
			</div>

		<!-- Product -->
			<div class="wrapper wrapper-style3">
				<article id="product">
					<header>
						<h2>Bridging gaps.</h2>
						<span>Engineering efficiency.</span>
					</header>
					<div class="container">
						<div class="row">
							<div class="12u">
							</div>
						</div>
						<div class="row">
							<div class="4u">
								<article class="box box-style2">
									<h3>Bind</a></h3>
									<p>Currently in beta, our flaship product helps researchers find top quality, commercially manufactured antibodies using a rating system and user-generated protocols. It's Amazon for antibody research.</p>
								</article>
							</div>
							<div class="4u">
								<article class="box box-style2">
									<h3>Health Informatics</h3>
									<p>Let's face it. Doctors need better, more efficient access to medical records in a secure way. We're developing a suite of tools to help doctor's offices effectively serve their patients, and retrieve the right information.</p>
								</article>
							</div>
							<div class="4u">
								<article class="box box-style2">
									<h3>Big Data</h3>
									<p>It's all about the numbers. Software is about to eat the healthcare industry, and we want to be spearheading the effort. We're searching new areas in the biotech industry to increase results.</p>
								</article>
							</div>
						</div>
					</div>
					<footer>
						<p>Ready to let us help you optimize your work?</p>
						<a href="#sign_up" class="button button-big">Sign Up</a>
					</footer>
				</article>
			</div>

		<!-- Contact -->
			<div class="wrapper wrapper-style4">
				<article id="sign_up" class="container small">
					<header>
						<h2>Sign Up</h2>
						<span>Start using Bind today.</span>
					</header>
					<div>
						<div class="row">
							<div class="12u">
								<form method="post" action="#">
									<div>
										<div class="row half">
											<div class="6u">
												<input type="text" name="name" id="name" placeholder="Name" />
											</div>
											<div class="6u">
												<input type="text" name="email" id="email" placeholder="Email" />
											</div>
										</div>
										<div class="row half">
											<div class="6u">
												<input type="text" name="password" id="subject" placeholder="Password" />
											</div>
											<div class="6u">
												<input type="text" name="password" id="subject" placeholder="Password Confirmation" />
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<a href="#" class="button form-button-submit">Submit</a>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
					<footer>
						<hr />
						<ul id="copyright">
							<li>&copy; 2013 Sciero. All Rights Reserved.</li>
						</ul>
					</footer>
				</article>
			</div>		
	</body>
</html>

app/views/pages/_users.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
    	<div class="well">
      	<p class="welcome">
      		Welcome, <%= current_user.name %>!
      	</p>
        <br />
        <br />
    	</div>
      <div class="nav">
        <%= link_to "Add Antibody", new_antibody_path, class: "btn btn-success" %>
        <%= link_to "Search Antibodies", antibodies_path, class: "btn btn-info" %>
      </div>
    </div>
    <!-- if user is signed in && no protocols are present, render alert for no protocols -->
		<% if @user.protocols.empty? %>
			<div class="span8">
				<div class="row">
					<div class="span6 offset3">
						<div class="text-center">
							<div class="alert alert-info">
								<button type="button" class="close" data-dismiss="alert">&times;</button>
								<strong>You have no protocols!</strong><br />
								To create a protocol, you may create an antibody from your profile,
								or search for an antibody.
							</div>
						</div>
					</div>
				</div>
			</div>
		<% else %>
		<!-- otherwise render list of user's protocols -->
	    <div class="span9">
	    	<div class="well">
	        <div class="accordion" id="accordion2">
	          <div class="accordion-group">
	            <div class="accordion-heading">
	              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
	               <li class="dropdown">
	               <p class="my_protocols">My Protocols (<%= current_user.protocols.count %>)<b class="caret"></b></p></li>
	              </a>
	            </div>
	            <div id="collapseOne" class="accordion-body collapse">
	              <div class="accordion-inner">
	                <p>
	                	<%= render :partial => 'protocols/protocol' %>
	                </p>
	              </div>
	            </div>
	          </div>
	        </div>
	    	</div>
	  	</div>
  	<% end %>
  </div>
</div>

app/views/pages/_welcome.html.erb
<div class="row-fluid">
	<div class="span4">
		<h3>What is Sciero?</h3>
		<div class="well">
			<p>
				Sciero is a startup out of Boston that is designing innovative tools at the intersection of deep information technology and biomedical research.
			</p>
			<p>
				<%= link_to "Learn More", about_path, class: "btn" %>
			</p>
		</div>
	</div>
	<div class="span4">
		<h3>Products</h3>
		<div class="well">
			<p>
				While other companies strive to adapt technology to the changes in science, Sciero is advancing technology to stay ahead of the curve.
			</p>
			<p>
				<%= link_to "Learn More", products_path, class: "btn" %>
			</p>
		</div>
	</div>
	<div class="span4">
		<h3>The Team</h3>
		<div class="well">
			<p>
				We're no amateurs. We're skilled entrepreneurs with a passion to serve. Client-oriented and forward-thinking. We do the work so you don't have to.
			</p>
			<p>
				<%= link_to "Learn More", team_path, class: "btn" %>
			</p>
		</div>
	</div>
</div>

app/views/pages/about.html.erb
<div class="page-header">
	<h1>About Sciero
		<p>
			<hr>
			<small>
					We take a high-level approach to every project and feature.
					<br />
					We aim to achieve the highest usability standard that is streamlined and accessible for every scientist.
					<br />
					It is our goal with the latest tools available to us in deep information technology to redefine the conventional scientific means of research by increasing the efficiency of data collection, documentation, management, and collaboration.
			</small>
		</p>
	</h1>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<%= render 'users/show' %>
<% else %>
	<div class="hero-unit">
		<div class="text-center">
			<div class="page-header">
				<h1>Sciero.	
				<p>
					<small>Scientific Research. Redefined.</small>
				</p>
				</h1>
			</div>
		</div>
		<div class="row-fluid">
      <div class="span4 offset4">
        <div class="span12">
          <div class="span6">
            <%= link_to "Register", new_user_registration_path, class: "btn btn-large btn-block btn-success" %>
          </div>
          <div class="span6">
            <%= link_to "Antibodies", antibodies_path, class: "btn btn-large btn-block btn-info" %>
          </div>
        </div>
      </div>
    </div> 
	</div>
	<%= render 'pages/welcome' %>
<% end %>

app/views/pages/products.html.erb
<div class="page-header">
	<h1>Product Development
		<p>
			<hr>
			<small>
					We have a number of products that we're developing which are designed to improve your work efficiency.
					<br /><br />
					Our flagship product is Bind. Through a simple rating and feedback system, users can determine the quality of any given commercially manufactured antibody with user-generated, testable protocols. This raises the standard of antibodies available on the market today.
					It's Amazon for antibody research.
			</small>
		</p>
	</h1>
</div>

app/views/pages/team.html.erb
<!-- <div class="page-header">
	<h1>The Team
		<p>
			<hr>
			<small>
					CEO
					<br /><br />
					CTO
					<br /><br />
					COO
			</small>
		</p>
	</h1>
</div> -->

app/views/protocols/edit.html.erb
<h1>Editing protocol</h1>

<%= render 'form' %>

<%= link_to 'Show', @protocol %> |
<%= link_to 'Back', protocols_path %>

app/views/protocols/index.html.erb
<h1>Listing Protocols</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>User Application Statement</th>
      <th>Research Application</th>
      <th>Cell or Tissue Model</th>
      <th>Summary</th>
      <th>Author</th>
    </tr>
  </thead>
  <tbody>
   <% @protocols.each do |protocol| %>
    <tr>
      <td><%= protocol.statement %></td>
      <td><%= protocol.research_application %></td>
      <td><%= protocol.cell %></td>
      <td><%= protocol.description %></td>
      <td><em><%= protocol.user.name %></em></td>
      <td><%= link_to 'Info', protocol, class: "btn btn-info" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Protocol', new_protocol_path %>

app/views/protocols/new.html.erb
<h1>New protocol</h1>

<%= render 'form' %>

<%= link_to 'Back', protocols_path %>

app/views/protocols/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <div class="well">
      <p>
        <b>User Application Statement:</b>
        <%= @protocol.statement %>
      </p>
      <p>
        <b>Research Application:</b>
        <%= @protocol.research_application %>
      </p>
      <p>
        <b>Cell/Tissue Model:</b>
        <%= @protocol.cell %>
      </p>
      <p>
        <b>Lysis Buffer:</b>
        <%= @protocol.lysis_buffer %>
      </p>
      <p>
        <b>Gel Percentage:</b>
        <%= @protocol.gel %>%
      </p>
      <p>
        <b>Membrane Type:</b>
        <%= @protocol.membrane %>
      </p>
      <p>
        <b>Transfer Conditions:</b>
        <%= @protocol.transfer %>
      </p>
      <p>
        <b>Blocking Buffer:</b>
        <%= @protocol.blocking_buffer %>
      </p>
      <p>
        <b>Primary Dilution with Incubation Time & Temp:</b>
        <%= @protocol.primary_description %>
      </p>
      <p>
        <b>Secondary Dilution with Incubation Time & Temp:</b>
        <%= @protocol.secondary_description %>
      </p>
      <p>
        <b>Washes:</b>
        <%= @protocol.washes %>
      </p>
      <p>
        <b>Detection Method:</b>
        <%= @protocol.detection %>
      </p>
      <p>
        <b>Summary:</b>
        <%= @protocol.description %>
      </p>
    
      <br />

      <% if current_user == @protocol.user %>
        <%= link_to 'Edit Protocol', edit_protocol_path(@protocol), class: "btn btn-primary" %>
        <%= link_to 'Destroy Protocol', @protocol, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>     
    </div>
  </div>
</div>

app/views/users/_show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
    	<div class="well">
      	<p class="welcome">
      		Welcome, <%= current_user.name %>!
      	</p>
        <%= image_tag current_user.image_url(:thumb) %>
        <br />
        <br />
    	</div>
        <%= link_to "Add Antibody", new_antibody_path, class: "btn btn-success" %>   
    </div>
    <!-- if user is signed in && no protocols are present, render alert for no protocols -->
		<% if @user.protocols.empty? %>
			<div class="span10">
				<div class="row">
					<div class="span6 offset3">
						<div class="text-center">
							<div class="alert alert-info">
								<button type="button" class="close" data-dismiss="alert">&times;</button>
								<strong>You have no protocols!</strong><br />
								To create a protocol, you may create an antibody from your profile,
								or search for an antibody.
							</div>
						</div>
					</div>
				</div>
			</div>
		<% else %>
		<!-- otherwise render list of user's protocols -->
	    <div class="span10">
        <div class="accordion" id="accordion2">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
             <li class="dropdown">
             <p class="my_protocols">My Protocols (<%= current_user.protocols.count %>)<b class="caret"></b></p></li>
            </a>
          </div>
          <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner">
              <p>
              	<%= render :partial => 'protocols/protocol' %>
              </p>
            </div>
          </div>
        </div>
	  	</div>
  	<% end %>
  </div>
</div>